Fix undefined package_json during Yarn install
When running rails stimulus_reflex:install on a new Rails app using
Yarn, the following error is raised:

  --- [yarn] ----
  rails aborted!
  NameError: undefined local variable or method `package_json'
  for #<Rails::Generators::AppGenerator...

Looks like it's a missing update from
https://github.com/stimulusreflex/stimulus_reflex/pull/655